In [1]:
%load_ext kedro.ipython

[03/31/26 14:59:10] INFO     Using 'C:\Users\W608-PCXX\Desktop\Nueva                                __init__.py:269
                             carpeta\kedro_pokemon\.venv\Lib\site-packages\kedro\framework\project\
                             rich_logging.yml' as logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   __init__.py:64

                    INFO     Registered line magic '%load_node'                                      __init__.py:66

                    INFO     Resolved project path as: C:\Users\W608-PCXX\Desktop\Nueva             __init__.py:181
                             carpeta\kedro_pokemon.
                             To set a different path, run '%reload_kedro <project_root>'

[03/31/26 14:59:14] INFO     Kedro is sending anonymous usage data with the sole purpose of improving plugin.py:242
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[03/31/26 14:59:15] INFO     Kedro project pokemon                                                  __init__.py:147

                    INFO     Defined global variable 'context', 'session', 'catalog' and            __init__.py:148
                             'pipelines'

In [4]:
climadb = catalog.load("weather_data")
climadb

[03/31/26 15:08:30] INFO     Loading data from weather_data (CSVDataset)...                    data_catalog.py:1048

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [9]:
climadb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Temperature           13200 non-null  float64
 1   Humidity              13200 non-null  int64
 2   Wind Speed            13200 non-null  float64
 3   Precipitation (%)     13200 non-null  float64
 4   Cloud Cover           13200 non-null  object
 5   Atmospheric Pressure  13200 non-null  float64
 6   UV Index              13200 non-null  int64
 7   Season                13200 non-null  object
 8   Visibility (km)       13200 non-null  float64
 9   Location              13200 non-null  object
 10  Weather Type          13200 non-null  object
dtypes: float64(5), int64(2), object(4)
memory usage: 1.1+ MB

In [10]:
climadb.describe()

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km)
count,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000,13200.000000
mean,19.127576,68.710833,9.832197,53.644394,1005.827896,4.005758,5.462917
std,17.386327,20.194248,6.908704,31.946541,37.199589,3.856600,3.371499
min,-25.000000,20.000000,0.000000,0.000000,800.120000,0.000000,0.000000
25%,4.000000,57.000000,5.000000,19.000000,994.800000,1.000000,3.000000
50%,21.000000,70.000000,9.000000,58.000000,1007.650000,3.000000,5.000000
75%,31.000000,84.000000,13.500000,82.000000,1016.772500,7.000000,7.500000
max,109.000000,109.000000,48.500000,109.000000,1199.210000,14.000000,20.000000