In [32]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [33]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [34]:
df = catalog.load("datos_practica")
df

[04/07/26 12:38:16] INFO     Loading data from datos_practica (CSVDataset)...                  ]8;id=876913;file://C:\Users\gmont\Desktop\practica\kedro_pokemon\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=667824;file://C:\Users\gmont\Desktop\practica\kedro_pokemon\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [35]:
df.drop(["Peak", "All Time Peak"], axis=1, inplace=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Actual gross                      20 non-null     object
 2   Adjusted gross (in 2022 dollars)  20 non-null     object
 3   Artist                            20 non-null     object
 4   Tour title                        20 non-null     object
 5   Year(s)                           20 non-null     object
 6   Shows                             20 non-null     int64
 7   Average gross                     20 non-null     object
 8   Ref.                              20 non-null     object
dtypes: int64(2), object(7)
memory usage: 1.5+ KB

In [37]:
df.columns = (df.columns
              .str.lower()
              .str.replace(" ", "_")
              .str.replace("\xa0", "_")
              .str.replace(r"[^\w]", "", regex=True))

In [38]:
cols_money = ["actual_gross", "adjusted_gross_in_2022_dollars", "average_gross"]

df[cols_money ] = (df[cols_money ]
                     .replace(r"[^0-9.]", "", regex=True)
                     .astype(float))

In [39]:
df["tour_title"] = (df["tour_title"]
                    .astype(str)
                    .replace([r"\[.*\]",r"[^a-zA-Z0-9\s&.:]"], "", regex=True)
                    .str.strip())

In [40]:
df["start_year"] = (df["years"].str.extract(r"(\d{4})")).astype(int)
df["end_year"] = (df["years"].str.extract(r"(\d{4})$")).astype(int)

In [41]:
df

,rank,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,years,shows,average_gross,ref,start_year,end_year
0,1,780000000.0,780000000.0,Taylor Swift,The Eras Tour,2023–2024,56,13928571.0,[1],2023,2024
1,2,579800000.0,579800000.0,Beyoncé,Renaissance World Tour,2023,56,10353571.0,[3],2023,2023
2,3,411000000.0,560622615.0,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294.0,[6],2008,2009
3,4,397300000.0,454751555.0,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795.0,[7],2018,2019
4,5,345675146.0,402844849.0,Taylor Swift,Reputation Stadium Tour,2018,53,6522173.0,[8],2018,2018
5,6,305158363.0,388978496.0,Madonna,The MDNA Tour,2012,88,3467709.0,[9],2012,2012
6,7,280000000.0,381932682.0,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405.0,[11],2008,2009
7,7,257600000.0,257600000.0,Pink,Summer Carnival,2023–2024,41,6282927.0,[12],2023,2024
8,9,256084556.0,312258401.0,Beyoncé,The Formation World Tour,2016,49,5226215.0,[13],2016,2016
9,10,250400000.0,309141878.0,Taylor Swift,The 1989 World Tour,2015,85,2945882.0,[14],2015,2015
10,11,229100000.0,283202896.0,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606.0,[15][16],2013,2014
11,12,227400000.0,295301479.0,Lady Gaga,The Monster Ball Tour,2009–2011,203,1118227.0,[18],2009,2011
12,13,204000000.0,251856802.0,Katy Perry,Prismatic World Tour,2014–2015,151,1350993.0,[19],2014,2015
13,14,200000000.0,299676265.0,Cher,Living Proof: The Farewell Tour,2002–2005,325,615385.0,[20],2002,2005
14,15,194000000.0,281617035.0,Madonna,Confessions Tour,2006,60,3233333.0,[5],2006,2006
15,16,184000000.0,227452347.0,Pink,The Truth About Love Tour,2013–2014,142,1295775.0,[22],2013,2014
16,17,170000000.0,213568571.0,Lady Gaga,Born This Way Ball,2012–2013,98,1734694.0,[d],2012,2013
17,18,169800000.0,207046755.0,Madonna,Rebel Heart Tour,2015–2016,82,2070732.0,[4],2015,2016
18,19,167700000.0,204486106.0,Adele,Adele Live 2016,2016–2017,121,1385950.0,[25],2016,2017
19,20,150000000.0,185423109.0,Taylor Swift,The Red Tour,2013–2014,86,1744186.0,[26],2013,2014